# Generated by Django 5.1.5 on 2025-05-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_topic_material_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='json',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='type',
            field=models.CharField(default={}, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='json',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
