# Generated by Django 5.1.5 on 2025-05-20 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_material_json_material_type_topic_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='topicOfExercise', to='main.topic'),
        ),
    ]
