# Generated by Django 5.1.5 on 2025-05-23 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_exercise_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='topicOfMaterial', to='main.topic'),
        ),
    ]
